version: '3.8'

services:
  ######################
  # fake-log-collector #
  ######################
  fake-log-collector:
    image: jhleeeme/fake-log-collector:latest
    container_name: fake-log-collector
    hostname: fake-log-collector
    stdin_open: true # -i option
    tty: true        # -t option
    volumes:
      - .:/workspace/
    depends_on:
      - master
      - kafka-single-node
      - influxdb
    networks:
      net:
        ipv4_address: 10.0.0.10

  ##########
  # Hadoop #
  ##########
  master:
    image: jhleeeme/hadoop:3.2.1-ubuntu18.04
    container_name: master
    hostname: master
    stdin_open: true # -i option
    tty: true        # -t option
    volumes:
      - .tmpfs/:/tmpfs
    environment:
      - WORKER_NUM=3
    depends_on:
      - worker-1
      - worker-2
      - worker-3
    networks:
      net:
        ipv4_address: 10.0.0.20

  worker-1:
    image: jhleeeme/hadoop:3.2.1-ubuntu18.04
    container_name: worker-1
    hostname: worker-1
    stdin_open: true # -i option
    tty: true        # -t option
    volumes:
      - .tmpfs/:/tmpfs
    networks:
      net:
        ipv4_address: 10.0.0.21

  worker-2:
    image: jhleeeme/hadoop:3.2.1-ubuntu18.04
    container_name: worker-2
    hostname: worker-2
    stdin_open: true # -i option
    tty: true        # -t option
    volumes:
      - .tmpfs/:/tmpfs
    networks:
      net:
        ipv4_address: 10.0.0.22

  worker-3:
    image: jhleeeme/hadoop:3.2.1-ubuntu18.04
    container_name: worker-3
    hostname: worker-3
    stdin_open: true # -i option
    tty: true        # -t option
    volumes:
      - .tmpfs/:/tmpfs
    networks:
      net:
        ipv4_address: 10.0.0.23

  #########
  # Kafka #
  #########
  kafka-single-node:
    image: jhleeeme/kafka-single-node:2.13-3.1.1-alpine
    container_name: kafka-single-node
    hostname: kafka-single-node
    restart: always
    stdin_open: true # -i option
    tty: true        # -t option
    volumes:
      - .tmpfs/:/tmpfs
    networks:
      net:
        ipv4_address: 10.0.0.30

  ############
  # InfluxDB #
  ############
  influxdb:
    image: influxdb:1.8-alpine
    container_name: influxdb
    hostname: influxdb
    restart: always
    ports:
      - 8086:8086
    volumes:
      - ./Dockers/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
    environment:
      TZ: "Asia/Seoul"
      INFLUXDB_DB: "fake_log WITH DURATION 2h REPLICATION 1 SHARD DURATION 1h NAME d_2h_sgd_1h_r_1"
    networks:
      net:
        ipv4_address: 10.0.0.40

  ############
  # Telegraf #
  ############
  telegraf:
    image: telegraf:1.25-alpine
    container_name: telegraf
    hostname: telegraf
    restart: always
    user: "telegraf:${DOCKER_SOCK_GROUP}"
    environment:
      TZ: "Asia/Seoul"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./Dockers/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - fake-log-collector
    networks:
      net:
        ipv4_address: 10.0.0.50

  ###########
  # Grafana #
  ###########
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana
    restart: always
    ports:
      - 3000:3000
    environment:
      TZ: "Asia/Seoul"
    depends_on:
      - influxdb
      - kafka-single-node
    networks:
      net:
        ipv4_address: 10.0.0.60

############
# Networks #
############
networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
    #external: true
