{
 "title": "Container_Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Docker Container", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "fake-log-collector",
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "container_image", "operator": "=", "value": "jhleeeme/fake-log-collector" }
     ]
    },
    {
     "alias": "kafka-single-node",
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "container_image", "operator": "=", "value": "jhleeeme/kafka-single-node" }
     ]
    },
    {
     "alias": "telegraf",
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "container_image", "operator": "=", "value": "telegraf" }
     ]
    },
    {
     "alias": "influxdb",
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "container_image", "operator": "=", "value": "influxdb" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "fake-log-collector",
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "container_image", "operator": "=", "value": "jhleeeme/fake-log-collector" }
     ]
    },
    {
     "alias": "kafka-single-node",
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "container_image", "operator": "=", "value": "jhleeeme/kafka-single-node" }
     ]
    },
    {
     "alias": "telegraf",
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "container_image", "operator": "=", "value": "telegraf" }
     ]
    },
    {
     "alias": "influxdb",
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "container_image", "operator": "=", "value": "influxdb" }
     ]
    }
   ]
  },
  {
   "title": "Total Network",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "fake-log-collector (Read)",
     "measurement": "docker_container_net",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "container_image", "operator": "=", "value": "jhleeeme/fake-log-collector" }
     ]
    },
    {
     "alias": "fake-log-collector (Write)",
     "measurement": "docker_container_net",
     "select": [
      [
       { "params": [ "tx_bytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "container_image", "operator": "=", "value": "jhleeeme/fake-log-collector" }
     ]
    },
    {
     "alias": "kafka-single-node (Read)",
     "measurement": "docker_container_net",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "container_image", "operator": "=", "value": "jhleeeme/kafka-single-node" }
     ]
    },
    {
     "alias": "kafka-single-node (Write)",
     "measurement": "docker_container_net",
     "select": [
      [
       { "params": [ "tx_bytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "container_image", "operator": "=", "value": "jhleeeme/kafka-single-node" }
     ]
    },
    {
     "alias": "telegraf (Read)",
     "measurement": "docker_container_net",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "container_image", "operator": "=", "value": "telegraf" }
     ]
    },
    {
     "alias": "telegraf (Write)",
     "measurement": "docker_container_net",
     "select": [
      [
       { "params": [ "tx_bytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "container_image", "operator": "=", "value": "telegraf" }
     ]
    },
    {
     "alias": "influxdb (Read)",
     "measurement": "docker_container_net",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "container_image", "operator": "=", "value": "influxdb" }
     ]
    },
    {
     "alias": "influxdb (Write)",
     "measurement": "docker_container_net",
     "select": [
      [
       { "params": [ "tx_bytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "container_image", "operator": "=", "value": "influxdb" }
     ]
    }
   ]
  },
  { "title": "Hadoop Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "master",
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=", "value": "master" }
     ]
    },
    {
     "alias": "worker-1",
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=", "value": "worker-1" }
     ]
    },
    {
     "alias": "worker-2",
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=", "value": "worker-2" }
     ]
    },
    {
     "alias": "worker-3",
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=", "value": "worker-3" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "master",
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=", "value": "master" }
     ]
    },
    {
     "alias": "worker-1",
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=", "value": "worker-1" }
     ]
    },
    {
     "alias": "worker-2",
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=", "value": "worker-2" }
     ]
    },
    {
     "alias": "worker-3",
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=", "value": "worker-3" }
     ]
    }
   ]
  }
 ]
}