{
 "title": "Fake Logs",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Nginx",
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "Nginx",
     "query": "SELECT remoteAddr, request, statusCode, bodyBytesSent\nFROM log\nWHERE (\"key\" = 'nginx') AND (time >= now() - 1h)\nORDER BY desc"
    }
   ]
  },
  {
   "title": "Nginx (statusCode != 200)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Nginx",
     "query": "SELECT count(statusCode)\nFROM log\nWHERE \"key\" = 'nginx' AND statusCode != 200"
    }
   ]
  },
  {
   "title": "Total request count",
   "type": "stat",
   "gridPos": { "h": 23, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Nginx",
     "query": "SELECT count(request)\nFROM log\nWHERE \"key\" = 'nginx'"
    },
    {
     "alias": "Apache",
     "query": "SELECT count(request)\nFROM log\nWHERE \"key\" = 'apache'"
    },
    {
     "alias": "Flask",
     "query": "SELECT count(msg)\nFROM log\nWHERE \"key\" = 'flask'"
    }
   ]
  },
  {
   "title": "Apache",
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 8 },
   "targets": [
    {
     "alias": "Apache",
     "query": "SELECT remoteAddr, request, statusCode, bodyBytesSent\nFROM log\nWHERE (\"key\" = 'apache') AND (time >= now() - 1h)\nORDER BY desc"
    }
   ]
  },
  {
   "title": "Apache (statusCode != 200)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Apache",
     "query": "SELECT count(statusCode)\nFROM log\nWHERE \"key\" = 'apache' AND statusCode != 200"
    }
   ]
  },
  {
   "title": "Flask",
   "type": "table",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 16 },
   "targets": [
    {
     "alias": "Nginx",
     "query": "SELECT msg, logLevel\nFROM log\nWHERE (\"key\" = 'flask') AND (time >= now() - 1h)\nORDER BY desc"
    }
   ]
  },
  {
   "title": "Flask (logLevel = 'ERROR')",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 13, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "flask",
     "query": "SELECT count(logLevel)\nFROM log\nWHERE \"key\" = 'flask' AND logLevel = 'ERROR'"
    }
   ]
  }
 ]
}